openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: API endpoints for user authentication with JSON parse error fixes

paths:
  /api/auth/signup:
    post:
      summary: Create a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "user@example.com"
                password:
                  type: string
                  minLength: 8
                  example: "securePassword123"
                name:
                  type: string
                  example: "John Doe"
              required:
                - email
                - password
                - name
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authentication
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        description: User UUID
                      email:
                        type: string
                        format: email
                      name:
                        type: string
                    required:
                      - id
                      - email
                      - name
                  message:
                    type: string
                    example: "Account created successfully"
        '400':
          description: Bad request - invalid input or duplicate email
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Email already registered"
                  message:
                    type: string
                    example: "Email already registered"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Signup failed"
                  message:
                    type: string
                    example: "Signup failed: detailed error message"

  /api/auth/login:
    post:
      summary: Authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "user@example.com"
                password:
                  type: string
                  example: "securePassword123"
              required:
                - email
                - password
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authentication
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        description: User UUID
                      email:
                        type: string
                        format: email
                      name:
                        type: string
                    required:
                      - id
                      - email
                      - name
                  message:
                    type: string
                    example: "Login successful"
        '400':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid credentials"
                  message:
                    type: string
                    example: "Invalid credentials"
        '401':
          description: Unauthorized - invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid credentials"
                  message:
                    type: string
                    example: "Invalid credentials"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Login failed"
                  message:
                    type: string
                    example: "Login failed: detailed error message"

  /api/auth/verify:
    get:
      summary: Verify authentication token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                    example: true
                  user_id:
                    type: string
                    description: User UUID
        '401':
          description: Invalid or expired token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Token verification failed"
                  message:
                    type: string
                    example: "Token has expired"

  /api/auth/session:
    get:
      summary: Get current session (Better Auth)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current session data
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  expiresAt:
                    type: string
                    format: date-time
        '401':
          description: No valid session

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: User UUID
        email:
          type: string
          format: email
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - email
        - name